language: node_js
node_js:
  - '9'
cache:
  directories:
    - ./node_modules
script:
  - npm run build
deploy:
  - provider: surge
    domain: getdumont.surge.sh
    skip_cleanup: true
    project: ./dist
    on: master

env:
  global:
    secure: RiOaWhSrcQaeMmtAUrjsiWBGhrYFT7SMw93kC0ofoonsR3f7trw1g99PKyebdRUU7T9Te4nictZOY4W5mgk1CF6I1y8Ojiqb3lbEqhfJ5HGvJT9o9MWtQ1q1tqvvtBllA1fpmzaUYp/yyMivR+r45pjHfQT+RswvcclIaEmnJr5O/s80wVnnl1+nJ7P9m55yeylhO192fQgVVoBIFPzVUr5PwKnKxaqAwmOEX7JHlvGzLtvf01qL+0a8Plgs6rPeDxBxgnwL5Ew//MOmv0MTohloQplej4giu0cwqBtANVblXBFWszqCIkkXwxRFUnWTOAJccmNLmypxp4x5BXoUA1+OdU/q0uU4FUicH/HTTG6kfUuzDQDN19a7sa9Hun1Wd9Bn+3TKQp3LJZ/YBL+m9ZpMJuRRC2muisW32k1I+JG+qN2qM7TChkh2U2+sg576KDS4e31mBolzpKSqRMDgku+oHpi/mFtGY40knuL/RizskMjy8RuDPcjAYIdE4tqenstSe5yi0Ja+Vc5Sml1pIX7pJmdrSjd2Q+LEjqr7j8r1jOxR9Ik8cDeRtmQjkGITTiAFMLbjOB7Jt6YhgaJZWDNTJ2PePN3vtgC3YROdpzX+KdT9NL7pWj2Qh/3yZDwEswKLBzgBjhnSmHnQRIcwe1zR/SxvZvhCVlkI4gDorrw=
